theme: jekyll-theme-cayman
title: Rob Jahn
description: Links to blogs, webinars, and various projects

section-headings-color: #0e57be !default;
body-text-color: #606c71 !default;
body-link-color: #1e6bb8 !default;
blockquote-text-color: #819198 !default;